package br.com.projeto.financas.webservices.client.mensageiro;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01
 * Generated source version: 2.2
 */
@WebServiceClient(name = "mensagemService", targetNamespace = "http://impl.mensagem.webservices.mensageiro.tjpr.gov/", wsdlLocation = "http://portal-dev.tjpr.net/mensageiro/webservices/mensagemService?wsdl")
public class MensagemService
        extends Service {

    private final static QName MENSAGEMSERVICE_QNAME = new QName("http://impl.mensagem.webservices.mensageiro.tjpr.gov/", "mensagemService");

    public MensagemService(URL wsdlLocation) {
        super(wsdlLocation, MENSAGEMSERVICE_QNAME);
    }

    public MensagemService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MENSAGEMSERVICE_QNAME, features);
    }

    public MensagemService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MensagemService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * @return returns MensagemWebServiceImpl
     */
    @WebEndpoint(name = "MensagemWebServiceImplPort")
    public MensagemWebServiceImpl getMensagemWebServiceImplPort() {
        return super.getPort(new QName("http://impl.mensagem.webservices.mensageiro.tjpr.gov/", "MensagemWebServiceImplPort"), MensagemWebServiceImpl.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns MensagemWebServiceImpl
     */
    @WebEndpoint(name = "MensagemWebServiceImplPort")
    public MensagemWebServiceImpl getMensagemWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.mensagem.webservices.mensageiro.tjpr.gov/", "MensagemWebServiceImplPort"), MensagemWebServiceImpl.class, features);
    }
}
